import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { afterEach, describe, expect, test, vi } from 'vitest';
import { generate } from '../src/generator.js';
import {
  compileGenerated,
  createSandbox,
  fixturePath,
  generateFixture,
  importCompiled,
  readFileTree,
  removeSandbox,
  startSpecificationServer,
} from './helpers/harness.js';

const sandboxes: string[] = [];

afterEach(async () => {
  await Promise.all(sandboxes.splice(0).map(removeSandbox));
});

async function createGenerated(fixtureName = 'core.openapi.json') {
  const sandbox = await createSandbox();
  sandboxes.push(sandbox);
  const output = join(sandbox, 'generated');
  await generateFixture(fixtureName, output);
  return { output, sandbox };
}

describe('generated SDK contract', () => {
  test('создаёт точный framework-agnostic набор файлов', async () => {
    const { output } = await createGenerated();
    const tree = await readFileTree(output);
    expect([...tree.keys()]).toEqual([
      'create-api-client.ts',
      'data-contracts.ts',
      'http-client.ts',
      'index.ts',
      'operations/create-pet.ts',
      'operations/get-pet.ts',
      'operations/index.ts',
      'operations/list-pets.ts',
      'operations/read-note.ts',
      'operations/submit-form.ts',
      'operations/upload-file.ts',
      'operations-tree.ts',
    ]);

    for (const [path, content] of tree) {
      const text = content.toString('utf8');
      expect(text, path).toContain('Generated by @gromlab/rest-api-codegen');
      expect(text, path).not.toContain('@ts-nocheck');
      expect(text, path).not.toMatch(/(?:useSWR|react-query|@tanstack|axios|graphql|export class Api\s)/i);
    }
  });

  test('генерирует contracts, imports, methods, content types и response formats', async () => {
    const { output } = await createGenerated();
    const contracts = await readFile(join(output, 'data-contracts.ts'), 'utf8');
    const getPet = await readFile(join(output, 'operations', 'get-pet.ts'), 'utf8');
    const createPet = await readFile(join(output, 'operations', 'create-pet.ts'), 'utf8');
    const upload = await readFile(join(output, 'operations', 'upload-file.ts'), 'utf8');
    const form = await readFile(join(output, 'operations', 'submit-form.ts'), 'utf8');
    const note = await readFile(join(output, 'operations', 'read-note.ts'), 'utf8');
    const list = await readFile(join(output, 'operations', 'list-pets.ts'), 'utf8');

    expect(contracts).toContain('export type PetStatus = "active" | "archived";');
    expect(contracts).toContain('description?: string | null;');
    expect(getPet).toContain('path: `/__rac_selected_route_6a91/pets/${id}`');
    expect(getPet).toContain('method: "GET"');
    expect(getPet).toContain('query: query');
    expect(getPet).toContain('format: "json"');
    expect(getPet).toMatch(/\.\.\.params,[\s\S]*secure: true/);
    expect(createPet).toContain('type: ContentType.Json');
    expect(createPet).not.toContain('secure: true');
    expect(upload).toContain('type: ContentType.FormData');
    expect(upload).toContain('format: "blob"');
    expect(form).toContain('type: ContentType.UrlEncoded');
    expect(note).toContain('format: "text"');
    expect(list).toMatch(/query: ListPetsParams = \{\}/);
  });

  test('строит полное operationsTree и root exports с .js specifiers', async () => {
    const { output } = await createGenerated();
    const tree = await readFile(join(output, 'operations-tree.ts'), 'utf8');
    const index = await readFile(join(output, 'index.ts'), 'utf8');
    expect(tree).toContain('pets: {');
    expect(tree).toContain('admin: {');
    expect(tree).toContain('getPet: getPet');
    expect(tree).toContain('createPet: createPet');
    expect(index).toContain('export * as operations from "./operations/index.js"');
    for (const match of index.matchAll(/from "([^"]+)"/g)) {
      expect(match[1]).toMatch(/\.js$/);
    }
  });

  test('empty API остаётся компилируемым полным каркасом', async () => {
    const { output } = await createGenerated('empty.openapi.json');
    const tree = await readFileTree(output);
    expect([...tree.keys()]).toEqual([
      'create-api-client.ts',
      'data-contracts.ts',
      'http-client.ts',
      'index.ts',
      'operations/index.ts',
      'operations-tree.ts',
    ]);
    expect((await readFile(join(output, 'operations', 'index.ts'), 'utf8'))).toContain('export {};');
    expect((await readFile(join(output, 'operations-tree.ts'), 'utf8'))).toContain('export const operationsTree = {} as const;');
    const compile = await compileGenerated(output);
    expect(compile.result.exitCode, compile.result.stdout + compile.result.stderr).toBe(0);
  });
});

describe('naming и escaping', () => {
  test('reserved identifiers, collisions, Unicode и prototype tags компилируются без потерь', async () => {
    const { output } = await createGenerated('naming.openapi.json');
    const tree = await readFileTree(output);
    const operationFiles = [...tree.keys()].filter((path) => path.startsWith('operations/') && path !== 'operations/index.ts');
    expect(operationFiles).toHaveLength(8);
    expect(new Set(operationFiles.map((path) => path.toLowerCase())).size).toBe(8);
    for (const path of operationFiles) {
      expect(path).toMatch(/^operations\/[a-z0-9-]+\.ts$/);
      expect(path).not.toContain('..');
    }

    const operationsTree = await readFile(join(output, 'operations-tree.ts'), 'utf8');
    expect(operationsTree).toContain('constructor: {');
    expect(operationsTree.match(/constructor: \{/g)).toHaveLength(1);
    expect(operationsTree).toContain('toString: {');
    expect(operationsTree).toContain('hasOwnProperty: {');
    expect(operationsTree).toContain('данные: {');
    const compile = await compileGenerated(output);
    expect(compile.result.exitCode, compile.result.stdout + compile.result.stderr).toBe(0);
  });

  test('опасные OpenAPI strings остаются данными и не исполняются', async () => {
    const { output } = await createGenerated('escaping.openapi.json');
    const compile = await compileGenerated(output, { emit: true });
    expect(compile.result.exitCode, compile.result.stdout + compile.result.stderr).toBe(0);
    const generatedRoot = join(compile.outputDir as string, 'generated');
    const sdk = await importCompiled<{
      HttpClient: new () => { baseUrl: string };
      probe: (client: { request: (params: unknown) => Promise<unknown> }) => Promise<unknown>;
    }>(generatedRoot, 'index.js');
    const request = vi.fn(async (params) => params);
    const params = await sdk.probe({ request });
    expect(new sdk.HttpClient().baseUrl).toBe('https://escape.example/";globalThis.__baseUrlInjection=true;//${value}');
    expect(params).toMatchObject({ path: '/literal-`-${globalThis.__pathInjection=true}', secure: true });
    for (const key of ['__baseUrlInjection', '__pathInjection', '__commentInjection', '__schemaInjection']) {
      expect((globalThis as Record<string, unknown>)[key]).toBeUndefined();
    }
  });

  test('создаёт fallback names без operationId и пустой baseUrl для нестрокового server url', async () => {
    const { output } = await createGenerated('fallback.openapi.json');
    const files = [...(await readFileTree(output)).keys()];
    expect(files).toContain('operations/get-root.ts');
    expect(files.some((path) => path.includes('delete'))).toBe(true);
    expect(await readFile(join(output, 'http-client.ts'), 'utf8')).toContain('public baseUrl = "";');
  });

  test('алиасит коллизии runtime imports и не импортирует ContentType из документации', async () => {
    const { output } = await createGenerated('runtime-name-collisions.openapi.json');
    const request = await readFile(join(output, 'operations', 'request.ts'), 'utf8');
    const descriptionOnly = await readFile(join(output, 'operations', 'description-only.ts'), 'utf8');

    expect(request).toContain('ApiRequestClient as RuntimeApiRequestClient');
    expect(request).toContain('RequestParams as RuntimeRequestParams');
    expect(request).toContain('ContentType as RuntimeContentType');
    expect(request).toContain('http: RuntimeApiRequestClient');
    expect(request).toContain('params: RuntimeRequestParams = {}');
    expect(request).toContain('type: RuntimeContentType.Json');
    expect(descriptionOnly).not.toContain('import { ContentType');

    const compile = await compileGenerated(output);
    expect(compile.result.exitCode, compile.result.stdout + compile.result.stderr).toBe(0);
  });
});

describe('generation lifecycle', () => {
  test('URL input загружается ровно один раз и совпадает с local output', async () => {
    const sandbox = await createSandbox();
    sandboxes.push(sandbox);
    const body = await readFile(fixturePath('core.openapi.json'), 'utf8');
    const server = await startSpecificationServer({ body });
    try {
      const localOutput = join(sandbox, 'local');
      const remoteOutput = join(sandbox, 'remote');
      await generateFixture('core.openapi.json', localOutput);
      await generate({ inputPath: server.url, outputPath: remoteOutput });
      expect(server.requests).toEqual(['GET /openapi.json']);
      const localTree = await readFileTree(localOutput);
      const remoteTree = await readFileTree(remoteOutput);
      expect([...remoteTree.keys()]).toEqual([...localTree.keys()]);
      for (const [path, content] of localTree) {
        expect(remoteTree.get(path)?.equals(content), path).toBe(true);
      }
    } finally {
      await server.close();
    }
  });

  test('повторная генерация удаляет stale files и восстанавливает изменённые generated files', async () => {
    const { output } = await createGenerated();
    const first = await readFileTree(output);
    await writeFile(join(output, 'swr.ts'), 'legacy');
    await writeFile(join(output, 'custom.ts'), 'manual');
    await writeFile(join(output, 'index.ts'), 'changed manually');
    const progress: string[] = [];
    const result = await generate(
      { inputPath: fixturePath('core.openapi.json'), outputPath: output },
      { onProgress: ({ phase }) => progress.push(phase) },
    );
    const second = await readFileTree(output);
    expect(result).toMatchObject({
      fileCount: 12,
      operationCount: 6,
      outputPath: output,
    });
    expect(result.modelCount).toBeGreaterThan(0);
    expect(result.durationMs).toBeGreaterThan(0);
    expect([...new Set(progress)]).toEqual([
      'load',
      'analyze',
      'contracts',
      'operations',
      'indexes',
    ]);
    expect([...second.keys()]).toEqual([...first.keys()]);
    for (const [path, content] of first) {
      expect(second.get(path)?.equals(content), path).toBe(true);
    }
  });

  test.each([
    ['invalid-json.json', 'Не удалось распарсить OpenAPI спецификацию как JSON'],
    ['root-array.json', 'OpenAPI спецификация должна быть JSON-объектом'],
    ['missing-version.openapi.json', 'Не указана версия OpenAPI'],
    ['missing-info.openapi.json', 'должна содержать объект `info`'],
    ['missing-paths.openapi.json', 'должна содержать объект `paths`'],
  ])('invalid fixture %s не повреждает предыдущий SDK', async (fixture, message) => {
    const { output } = await createGenerated();
    const before = await readFileTree(output);
    await expect(generateFixture(fixture, output)).rejects.toThrow(message);
    const after = await readFileTree(output);
    expect([...after.keys()]).toEqual([...before.keys()]);
    for (const [path, content] of before) {
      expect(after.get(path)?.equals(content), path).toBe(true);
    }
  });

  test('HTTP error не создаёт output', async () => {
    const sandbox = await createSandbox();
    sandboxes.push(sandbox);
    const output = join(sandbox, 'generated');
    const server = await startSpecificationServer({ body: '{}', status: 503 });
    try {
      await expect(generate({ inputPath: server.url, outputPath: output })).rejects.toThrow('503 Service Unavailable');
      await expect(readFileTree(output)).rejects.toThrow();
    } finally {
      await server.close();
    }
  });

  test('malformed JSON по URL имеет отдельную parse error', async () => {
    const sandbox = await createSandbox();
    sandboxes.push(sandbox);
    const server = await startSpecificationServer({ body: '{ invalid' });
    try {
      await expect(generate({ inputPath: server.url, outputPath: join(sandbox, 'generated') }))
        .rejects.toThrow('Не удалось распарсить OpenAPI спецификацию как JSON');
    } finally {
      await server.close();
    }
  });

  test('network failure переводится в понятную ошибку', async () => {
    const sandbox = await createSandbox();
    sandboxes.push(sandbox);
    const server = await startSpecificationServer({ body: '{}' });
    const url = server.url;
    await server.close();
    await expect(generate({ inputPath: url, outputPath: join(sandbox, 'generated') }))
      .rejects.toThrow('Не удалось подключиться к OpenAPI спецификации');
  });
});

describe('strict generated consumer', () => {
  test('NodeNext consumer использует root, namespace, tree и direct operation', async () => {
    const { output } = await createGenerated();
    const compile = await compileGenerated(output, {
      consumerSource: `
        import { createApiClient, getPet, operations, operationsTree } from './generated/index.js';
        import type { ApiRequestClient, Pet } from './generated/index.js';

        const client: ApiRequestClient = {
          request: async <T>() => ({ id: '1', name: 'Rex', status: 'active' }) as T,
        };
        const api = createApiClient(client, operationsTree);
        const direct: Promise<Pet> = getPet(client, { id: '1' });
        const namespaced: Promise<Pet> = operations.getPet(client, { id: '1' });
        const bound: Promise<Pet> = api.pets.getPet({ id: '1' });
        void [direct, namespaced, bound];
      `,
    });
    expect(compile.result.exitCode, compile.result.stdout + compile.result.stderr).toBe(0);
  });

  test('generated HttpClient выполняет тот же базовый runtime contract', async () => {
    const { output } = await createGenerated();
    const compile = await compileGenerated(output, { emit: true });
    expect(compile.result.exitCode, compile.result.stdout + compile.result.stderr).toBe(0);
    const generatedRoot = join(compile.outputDir as string, 'generated');
    const sdk = await importCompiled<{
      ContentType: { Json: string; FormData: string };
      HttpClient: new (config: Record<string, unknown>) => {
        baseUrl: string;
        request: (params: Record<string, unknown>) => Promise<unknown>;
      };
      getPet: (
        client: { request: (params: Record<string, unknown>) => Promise<unknown> },
        input: { id: string },
        params: { secure?: boolean },
      ) => Promise<unknown>;
    }>(generatedRoot, 'index.js');
    const calls: Array<{ input: unknown; init: RequestInit | undefined }> = [];
    const client = new sdk.HttpClient({
      customFetch: async (input: unknown, init: RequestInit | undefined) => {
        calls.push({ input, init });
        return Response.json({ ok: true });
      },
    });
    await expect(client.request({
      path: '/runtime', method: 'POST', query: { values: [1, undefined, 2], empty: [] },
      body: false, type: sdk.ContentType.Json, format: 'json',
    })).resolves.toEqual({ ok: true });
    expect(client.baseUrl).toBe('https://contract.example/v1');
    expect(calls[0]?.input).toBe('https://contract.example/v1/runtime?values=1&values=2');
    expect(calls[0]?.init?.body).toBe('false');

    const secureRequest = vi.fn(async (params) => params);
    await expect(sdk.getPet({ request: secureRequest }, { id: '42' }, { secure: false })).resolves.toMatchObject({
      secure: true,
    });
  });
});
