import {
  generateApi as swaggerGenerateApi,
  type GenerateApiConfiguration,
  type GenerateApiOutput,
  type Hooks,
  type ParsedRoute,
} from 'swagger-typescript-api';
import { Biome, Distribution } from '@biomejs/js-api';
import { Eta } from 'eta';
import { existsSync } from 'node:fs';
import { mkdir, rm } from 'node:fs/promises';
import { performance } from 'node:perf_hooks';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { GeneratorConfig } from './config.js';
import { readTextFile, writeFileWithDirs } from './utils/file.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GENERATED_FILE_PREFIX = `/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */`;

type OperationFileInfo = {
  route: ParsedRoute;
  operationName: string;
  operationFileName: string;
};

type OperationTreeGroup = {
  moduleName: string;
  operations: OperationFileInfo[];
};

type PreparedSpecification = {
  spec: Record<string, unknown>;
  restoreTags: (configuration: GenerateApiConfiguration) => void;
};

type TypeScriptFormatter = {
  format: (content: string, filePath: string) => string;
  shutdown: () => void;
};

type GeneratedOutputWriter = {
  outputDir: string;
  fileCount: number;
};

type OperationRuntimeNames = {
  apiRequestClient: string;
  requestParams: string;
  contentType: string;
};

type DataContractsImport = {
  content: string;
  names: string[];
};

type UpstreamCodeGenProcess = Parameters<NonNullable<Hooks['onInit']>>[1];

export type GenerationPhase = 'load' | 'analyze' | 'contracts' | 'operations' | 'indexes';

export type GenerationProgress = {
  phase: GenerationPhase;
  current?: number;
  total?: number;
  elapsedMs: number;
};

export type GenerationOptions = {
  onProgress?: (progress: GenerationProgress) => void;
};

export type GenerationResult = {
  outputPath: string;
  fileCount: number;
  modelCount: number;
  operationCount: number;
  durationMs: number;
  timings: Record<GenerationPhase, number>;
};

const DEFAULT_BASE_URL_DECLARATION = "public baseUrl = '';";

const RESERVED_IDENTIFIERS = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
  'await',
  'arguments',
  'eval',
  'let',
  'static',
  'implements',
  'interface',
  'package',
  'private',
  'protected',
  'public',
]);

const PROTOTYPE_PROPERTY_NAMES = new Set(Object.getOwnPropertyNames(Object.prototype));
const HTTP_METHODS = new Set(['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']);
const CONTENT_TYPE_REQUEST_KINDS = new Set(['JSON', 'JSON_API', 'URL_ENCODED', 'FORM_DATA', 'TEXT']);
const TYPESCRIPT_IDENTIFIER_PATTERN = /[$_\p{ID_Start}][$\u200C\u200D\p{ID_Continue}]*/gu;

function createGenerationTracker(onProgress: GenerationOptions['onProgress']) {
  const startedAt = performance.now();
  const timings: Record<GenerationPhase, number> = {
    load: 0,
    analyze: 0,
    contracts: 0,
    operations: 0,
    indexes: 0,
  };
  let activePhase: GenerationPhase | undefined;
  let phaseStartedAt = startedAt;

  const completeActivePhase = (now: number): void => {
    if (activePhase) {
      timings[activePhase] += now - phaseStartedAt;
    }
  };

  const emit = (current?: number, total?: number): void => {
    if (activePhase) {
      onProgress?.({ phase: activePhase, current, total, elapsedMs: performance.now() - startedAt });
    }
  };

  return {
    start: (phase: GenerationPhase, total?: number): void => {
      const now = performance.now();
      completeActivePhase(now);
      activePhase = phase;
      phaseStartedAt = now;
      emit(total === undefined ? undefined : 0, total);
    },
    update: (current: number, total?: number): void => emit(current, total),
    finish: (): Pick<GenerationResult, 'durationMs' | 'timings'> => {
      const now = performance.now();
      completeActivePhase(now);
      activePhase = undefined;
      return { durationMs: now - startedAt, timings };
    },
  };
}

function compareStrings(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function compareOperationFiles(left: OperationFileInfo, right: OperationFileInfo): number {
  return compareStrings(`${left.operationFileName}.js`, `${right.operationFileName}.js`);
}

function toWords(value: string): string[] {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}

function toCamelCase(value: string): string {
  const words = toWords(value);
  if (!words.length) {
    return '';
  }

  const [firstWord = '', ...restWords] = words;
  return [
    firstWord.toLowerCase(),
    ...restWords.map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()),
  ].join('');
}

function toKebabCase(value: string): string {
  return toWords(value).map((word) => word.toLowerCase()).join('-');
}

function createFallbackRouteName(route: ParsedRoute): string {
  return toCamelCase(`${route.raw.method} ${route.raw.route}`) || 'operation';
}

function createSafeIdentifier(value: string, fallback: string): string {
  const identifier = value.replace(/[^A-Za-z0-9_$]/g, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '');
  const safeIdentifier = identifier || fallback;

  if (RESERVED_IDENTIFIERS.has(safeIdentifier)) {
    const safeFallback = fallback.replace(/[^A-Za-z0-9_$]/g, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '');

    if (safeFallback && !RESERVED_IDENTIFIERS.has(safeFallback) && /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(safeFallback)) {
      return safeFallback;
    }

    return `${safeIdentifier}Operation`;
  }

  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(safeIdentifier)) {
    return safeIdentifier;
  }

  return `operation${safeIdentifier.charAt(0).toUpperCase()}${safeIdentifier.slice(1)}`;
}

function createUniqueName(baseName: string, usedNames: Set<string>): string {
  let name = baseName;
  let counter = 2;

  while (usedNames.has(name)) {
    name = `${baseName}${counter}`;
    counter += 1;
  }

  usedNames.add(name);
  return name;
}

function getAllRoutes(configuration: GenerateApiConfiguration): ParsedRoute[] {
  return [
    ...(configuration.routes.outOfModule || []),
    ...(configuration.routes.combined || []).flatMap(({ routes }) => routes || []),
  ];
}

function createOperationFiles(routes: ParsedRoute[]): OperationFileInfo[] {
  const usedOperationNames = new Set<string>();
  const usedFileNames = new Set<string>();

  return routes.map((route) => {
    const fallbackRouteName = createFallbackRouteName(route);
    const operationName = createUniqueName(
      createSafeIdentifier(route.routeName.usage || fallbackRouteName, fallbackRouteName),
      usedOperationNames,
    );
    const operationFileName = createUniqueName(
      toKebabCase(operationName) || toKebabCase(fallbackRouteName) || 'operation',
      usedFileNames,
    );

    return {
      route,
      operationName,
      operationFileName,
    };
  });
}

function addModelTypeIdentifiers(
  content: unknown,
  modelNames: ReadonlySet<string>,
  importedNames: Set<string>,
): void {
  if (typeof content !== 'string') {
    return;
  }

  for (const [identifier] of content.matchAll(TYPESCRIPT_IDENTIFIER_PATTERN)) {
    if (identifier && modelNames.has(identifier)) {
      importedNames.add(identifier);
    }
  }
}

function createDataContractsImport(
  route: ParsedRoute,
  configuration: GenerateApiConfiguration,
  modelNames: ReadonlySet<string>,
): DataContractsImport {
  const importedNames = new Set<string>();
  const { parameters, payload, query, requestParams } = route.request;
  const parameterValues = Array.isArray(parameters)
    ? parameters
    : parameters && typeof parameters === 'object'
      ? Object.values(parameters)
      : [];

  addModelTypeIdentifiers(route.response.type, modelNames, importedNames);
  addModelTypeIdentifiers(route.response.errorType, modelNames, importedNames);
  addModelTypeIdentifiers(payload?.type, modelNames, importedNames);

  if (configuration.config.extractRequestParams && requestParams) {
    addModelTypeIdentifiers(
      configuration.utils.getInlineParseContent(
        requestParams as Parameters<typeof configuration.utils.getInlineParseContent>[0],
      ),
      modelNames,
      importedNames,
    );
  } else {
    for (const parameter of parameterValues) {
      addModelTypeIdentifiers((parameter as { type?: unknown }).type, modelNames, importedNames);
    }
    addModelTypeIdentifiers((query as { type?: unknown } | undefined)?.type, modelNames, importedNames);
  }

  if (!importedNames.size) {
    return { content: '', names: [] };
  }

  const names = [...importedNames].sort((a, b) => a.localeCompare(b));
  return {
    content: `import type { ${names.join(', ')} } from "../data-contracts.js";`,
    names,
  };
}

function createRuntimeImportName(sourceName: string, occupiedNames: Set<string>): string {
  if (!occupiedNames.has(sourceName)) {
    occupiedNames.add(sourceName);
    return sourceName;
  }

  const baseName = `Runtime${sourceName}`;
  let name = baseName;
  let suffix = 2;
  while (occupiedNames.has(name)) {
    name = `${baseName}${suffix++}`;
  }
  occupiedNames.add(name);
  return name;
}

function createOperationRuntimeNames(dataContractNames: string[]): OperationRuntimeNames {
  const occupiedNames = new Set(dataContractNames);
  return {
    apiRequestClient: createRuntimeImportName('ApiRequestClient', occupiedNames),
    requestParams: createRuntimeImportName('RequestParams', occupiedNames),
    contentType: createRuntimeImportName('ContentType', occupiedNames),
  };
}

function createImportSpecifier(sourceName: string, localName: string): string {
  return sourceName === localName ? sourceName : `${sourceName} as ${localName}`;
}

function createHttpClientImport(route: ParsedRoute, runtimeNames: OperationRuntimeNames): string {
  const imports = [
    `import type { ${[
      createImportSpecifier('ApiRequestClient', runtimeNames.apiRequestClient),
      createImportSpecifier('RequestParams', runtimeNames.requestParams),
    ].join(', ')} } from "../http-client.js";`,
  ];

  if (CONTENT_TYPE_REQUEST_KINDS.has(route.requestBodyInfo?.contentKind || '')) {
    imports.push(
      `import { ${createImportSpecifier('ContentType', runtimeNames.contentType)} } from "../http-client.js";`,
    );
  }

  return imports.join('\n');
}

function createObjectPropertyKey(name: string): string {
  return JSON.stringify(name);
}

function createOperationTreePropertyName(operationFile: OperationFileInfo): string {
  return operationFile.route.routeName.usage || operationFile.operationName;
}

function createOperationTreeContent(configuration: GenerateApiConfiguration, operationFiles: OperationFileInfo[]): string {
  const operationByRoute = new Map(operationFiles.map((operationFile) => [operationFile.route, operationFile]));
  const imports = operationFiles.toSorted(compareOperationFiles).map(
    (operationFile) =>
      `import { ${operationFile.operationName} } from "./operations/${operationFile.operationFileName}.js";`,
  );
  const outOfModuleOperations = (configuration.routes.outOfModule || [])
    .map((route) => operationByRoute.get(route))
    .filter((operationFile): operationFile is OperationFileInfo => Boolean(operationFile));
  const operationTreeGroups: OperationTreeGroup[] = (configuration.routes.combined || []).map(({ moduleName, routes }) => ({
    moduleName,
    operations: (routes || [])
      .map((route) => operationByRoute.get(route))
      .filter((operationFile): operationFile is OperationFileInfo => Boolean(operationFile)),
  }));
  const lines = [
    ...imports,
    '',
    'export const operationsTree = {',
  ];

  const rootPropertyNames = new Set<string>();

  for (const operationFile of outOfModuleOperations) {
    const propertyName = createUniqueName(createOperationTreePropertyName(operationFile), rootPropertyNames);
    lines.push(`  ${createObjectPropertyKey(propertyName)}: ${operationFile.operationName},`);
  }

  for (const { moduleName, operations } of operationTreeGroups) {
    const groupName = createUniqueName(moduleName, rootPropertyNames);
    lines.push(`  ${createObjectPropertyKey(groupName)}: {`);
    const groupPropertyNames = new Set<string>();

    for (const operationFile of operations) {
      const propertyName = createUniqueName(createOperationTreePropertyName(operationFile), groupPropertyNames);
      lines.push(`    ${createObjectPropertyKey(propertyName)}: ${operationFile.operationName},`);
    }

    lines.push('  },');
  }

  lines.push('} as const;', '', 'export type OperationsTree = typeof operationsTree;');

  return lines.join('\n');
}

function getEmbeddedClientSourcePath(templatesPath: string, fileName: string): string {
  const sourcePath = resolve(__dirname, 'client', fileName);
  return existsSync(sourcePath) ? sourcePath : resolve(templatesPath, fileName);
}

async function renderHttpClient(templatesPath: string, spec: Record<string, unknown>): Promise<string> {
  const source = await readTextFile(getEmbeddedClientSourcePath(templatesPath, 'http-client.ts'));
  const servers = Array.isArray(spec.servers) ? spec.servers : [];
  const firstServer = servers[0];
  const baseUrl = firstServer && typeof firstServer === 'object' && 'url' in firstServer
    ? (firstServer as { url?: unknown }).url
    : '';
  const replacement = `public baseUrl = ${JSON.stringify(typeof baseUrl === 'string' ? baseUrl : '')};`;

  if (
    !source.includes(DEFAULT_BASE_URL_DECLARATION) ||
    source.indexOf(DEFAULT_BASE_URL_DECLARATION) !== source.lastIndexOf(DEFAULT_BASE_URL_DECLARATION)
  ) {
    throw new Error('Не удалось подготовить HttpClient: ожидается одно стандартное объявление baseUrl.');
  }

  return source.replace(DEFAULT_BASE_URL_DECLARATION, replacement);
}

async function createTypeScriptFormatter(): Promise<TypeScriptFormatter> {
  const biome = await Biome.create({ distribution: Distribution.NODE });
  try {
    const project = biome.openProject();
    biome.applyConfiguration(project.projectKey, {
      files: { maxSize: Number.MAX_SAFE_INTEGER },
      formatter: { indentStyle: 'space' },
    });

    return {
      format: (content, filePath) => biome.formatContent(project.projectKey, content, { filePath }).content,
      shutdown: () => biome.shutdown(),
    };
  } catch (error) {
    biome.shutdown();
    throw error;
  }
}

function cacheUpstreamTemplates(codeGenProcess: UpstreamCodeGenProcess): void {
  const eta = new Eta({ functionHeader: 'const includeFile = options.includeFile;' });
  const compiledTemplates = new Map<string, ReturnType<typeof eta.compile>>();
  const includedTemplates = new Map<string, string>();
  const renderTemplateData = codeGenProcess.getRenderTemplateData();

  const renderTemplate = (template: string, configuration: Record<string, unknown>): string => {
    if (!template) {
      return '';
    }

    let compiledTemplate = compiledTemplates.get(template);
    if (!compiledTemplate) {
      compiledTemplate = eta.compile(template, { async: false });
      compiledTemplates.set(template, compiledTemplate);
    }

    return eta.render(compiledTemplate, {
      ...renderTemplateData,
      ...configuration,
    }, {
      includeFile: (path: string, includeConfiguration: Record<string, unknown>) => {
        let includedTemplate = includedTemplates.get(path);
        if (includedTemplate === undefined) {
          includedTemplate = codeGenProcess.templatesWorker.getTemplateContent(path);
          includedTemplates.set(path, includedTemplate);
        }
        return renderTemplate(includedTemplate, includeConfiguration);
      },
    } as never);
  };

  codeGenProcess.templatesWorker.renderTemplate = renderTemplate;
}

async function writeFormattedFile(
  formatter: TypeScriptFormatter,
  writer: GeneratedOutputWriter,
  relativePath: string,
  content: string,
): Promise<void> {
  const formattedContent = formatter.format(`${GENERATED_FILE_PREFIX}\n\n${content}`, relativePath);
  await writeGeneratedFile(writer, relativePath, formattedContent);
}

async function writeGeneratedFile(
  writer: GeneratedOutputWriter,
  relativePath: string,
  content: string,
): Promise<void> {
  await writeFileWithDirs(join(writer.outputDir, relativePath), content);
  writer.fileCount += 1;
}

function validateSpecification(spec: Record<string, unknown>): void {
  if (typeof spec.openapi !== 'string' && typeof spec.swagger !== 'string') {
    throw new Error('Не указана версия OpenAPI (`openapi`) или Swagger (`swagger`).');
  }

  if (!spec.info || typeof spec.info !== 'object' || Array.isArray(spec.info)) {
    throw new Error('OpenAPI спецификация должна содержать объект `info`.');
  }

  if (!spec.paths || typeof spec.paths !== 'object' || Array.isArray(spec.paths)) {
    throw new Error('OpenAPI спецификация должна содержать объект `paths`.');
  }
}

function prepareSpecification(spec: Record<string, unknown>): PreparedSpecification {
  const internalToOriginalTag = new Map<string, string>();
  const originalToInternalTag = new Map<string, string>();
  const paths = spec.paths as Record<string, unknown>;
  let tagIndex = 0;

  for (const pathItem of Object.values(paths)) {
    if (!pathItem || typeof pathItem !== 'object' || Array.isArray(pathItem)) {
      continue;
    }

    for (const [method, operation] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method.toLowerCase()) || !operation || typeof operation !== 'object' || Array.isArray(operation)) {
        continue;
      }

      const tags = (operation as { tags?: unknown }).tags;
      if (!Array.isArray(tags)) {
        continue;
      }

      (operation as { tags: unknown[] }).tags = tags.map((tag) => {
        if (typeof tag !== 'string' || !PROTOTYPE_PROPERTY_NAMES.has(tag)) {
          return tag;
        }

        const existingInternalTag = originalToInternalTag.get(tag);
        if (existingInternalTag) {
          return existingInternalTag;
        }

        const internalTag = `restApiCodegenTag${tagIndex++}`;
        originalToInternalTag.set(tag, internalTag);
        internalToOriginalTag.set(internalTag, tag);
        return internalTag;
      });
    }
  }

  return {
    spec,
    restoreTags: (configuration) => {
      for (const group of configuration.routes.combined || []) {
        const originalTag = internalToOriginalTag.get(group.moduleName);
        if (originalTag) {
          group.moduleName = originalTag;
        }

        for (const route of group.routes || []) {
          route.raw.tags = (route.raw.tags || []).map((tag) => internalToOriginalTag.get(tag) || tag);
        }
      }
    },
  };
}

async function loadSpecification(inputPath: string): Promise<Record<string, unknown>> {
  const isUrl = inputPath.startsWith('http://') || inputPath.startsWith('https://');
  let content: string;

  if (isUrl) {
    let response: Response;

    try {
      response = await fetch(inputPath);
    } catch (error) {
      const details = error instanceof Error ? translateGenerationErrorMessage(error.message) : String(error);
      throw new Error(
        `Не удалось подключиться к OpenAPI спецификации: ${inputPath}. ` +
          `Проверьте доступность URL и сетевое подключение. Детали: ${details}`,
      );
    }

    if (!response.ok) {
      throw new Error(
        `Не удалось загрузить OpenAPI спецификацию из ${inputPath}: ${response.status} ${response.statusText}`,
      );
    }

    content = await response.text();
  } else {
    content = await readTextFile(resolve(inputPath));
  }

  let specification: unknown;

  try {
    specification = JSON.parse(content) as unknown;
  } catch (error) {
    const details = error instanceof Error ? error.message : String(error);
    throw new Error(`Не удалось распарсить OpenAPI спецификацию как JSON. Детали: ${details}`);
  }

  if (!specification || typeof specification !== 'object' || Array.isArray(specification)) {
    throw new Error('OpenAPI спецификация должна быть JSON-объектом.');
  }

  const spec = specification as Record<string, unknown>;
  validateSpecification(spec);
  return spec;
}

function translateGenerationErrorMessage(message: string): string {
  return message
    .replace(
      'Unable to connect. Is the computer able to access the url?',
      'Не удалось подключиться к URL. Проверьте доступность OpenAPI спецификации и сетевое подключение.',
    )
    .replace('fetch failed', 'не удалось выполнить сетевой запрос')
    .replace('request timeout', 'истекло время ожидания запроса')
    .replace('socket hang up', 'соединение было разорвано')
    .replace('ECONNREFUSED', 'соединение отклонено')
    .replace('ENOTFOUND', 'хост не найден')
    .replace('ETIMEDOUT', 'истекло время ожидания соединения');
}

/**
 * Генерация API клиента из OpenAPI спецификации
 */
export async function generate(config: GeneratorConfig, options: GenerationOptions = {}): Promise<GenerationResult> {
  const templatesPath = resolve(__dirname, 'templates');
  const tracker = createGenerationTracker(options.onProgress);
  let formatter: TypeScriptFormatter | undefined;

  if (!existsSync(templatesPath)) {
    throw new Error(
      `Директория шаблонов не найдена: ${templatesPath}. ` +
        'Проверьте, что пакет собран корректно (npm run build).',
    );
  }

  try {
    const outputDir = resolve(config.outputPath);
    tracker.start('load');
    const spec = await loadSpecification(config.inputPath);
    const preparedSpecification = prepareSpecification(spec);
    let analyzedOperations = 0;
    tracker.start('analyze');
    const activeFormatter = await createTypeScriptFormatter();
    formatter = activeFormatter;
    const generatorOutput = await swaggerGenerateApi({
      spec: preparedSpecification.spec,
      httpClientType: 'fetch',
      modular: false,
      templates: templatesPath,
      generateClient: false,
      generateRouteTypes: false,
      generateUnionEnums: true,
      extractRequestParams: true,
      extractRequestBody: true,
      extractEnums: true,
      cleanOutput: false,
      unwrapResponseData: true,
      defaultResponseAsSuccess: true,
      enumNamesAsValues: false,
      moduleNameFirstTag: true,
      extraTemplates: [],
      addReadonly: false,
      sortTypes: false,
      sortRoutes: false,
      extractResponseError: false,
      fixInvalidEnumKeyPrefix: 'KEY',
      silent: true,
      defaultResponseType: 'void',
      typePrefix: '',
      typeSuffix: '',
      enumKeyPrefix: '',
      enumKeySuffix: '',
      extractingOptions: {
        requestBodySuffix: ['Payload', 'Body', 'Input'],
        requestParamsSuffix: ['Params'],
        responseBodySuffix: ['Data', 'Result', 'Output'],
        responseErrorSuffix: ['Error', 'Fail', 'Fails', 'ErrorData', 'HttpError', 'BadResponse'],
      },
      hooks: {
        onInit: (configuration, codeGenProcess) => {
          // data-contracts.ts has no imports, so parsing the multi-megabyte file in a language service is a no-op.
          codeGenProcess.codeFormatter.removeUnusedImports = (content) => content;
          codeGenProcess.codeFormatter.format = async (content) =>
            activeFormatter.format(content, 'data-contracts.ts');
          cacheUpstreamTemplates(codeGenProcess);
          return configuration;
        },
        onCreateRoute: (route: ParsedRoute) => {
          analyzedOperations += 1;
          if (analyzedOperations % 10 === 0) {
            tracker.update(analyzedOperations);
          }
          return route;
        },
        onFormatRouteName: (_routeInfo: unknown, templateRouteName: string) => {
          const match = templateRouteName.match(/^(\w+)Controller(\w+)$/);
          const methodName = match?.[2];

          return methodName
            ? methodName.charAt(0).toLowerCase() + methodName.slice(1)
            : templateRouteName;
        },
      },
      output: false,
      fileName: 'index.ts',
    } as Parameters<typeof swaggerGenerateApi>[0]) as unknown as GenerateApiOutput;
    tracker.update(analyzedOperations);
    preparedSpecification.restoreTags(generatorOutput.configuration);

    const dataContractsFile = generatorOutput.files[0];
    if (!dataContractsFile) {
      throw new Error('Генератор не вернул содержимое data-contracts.ts.');
    }

    const operationFiles = createOperationFiles(getAllRoutes(generatorOutput.configuration));
    const modelNames = new Set(generatorOutput.configuration.modelTypes.map(({ name }) => name));
    tracker.start('contracts');
    await rm(outputDir, { recursive: true, force: true });
    await mkdir(outputDir, { recursive: true });
    const writer: GeneratedOutputWriter = { outputDir, fileCount: 0 };

    await writeGeneratedFile(
      writer,
      'data-contracts.ts',
      `${GENERATED_FILE_PREFIX}\n\n${dataContractsFile.fileContent}`,
    );

    await writeFormattedFile(
      activeFormatter,
      writer,
      'http-client.ts',
      await renderHttpClient(templatesPath, spec),
    );

    await writeFormattedFile(
      activeFormatter,
      writer,
      'create-api-client.ts',
      await readTextFile(getEmbeddedClientSourcePath(templatesPath, 'create-api-client.ts')),
    );

    const operationTemplatePath = join(templatesPath, 'operation.ejs');
    const operationTemplate = await readTextFile(operationTemplatePath);
    tracker.start('operations', operationFiles.length);

    for (const [index, operationFile] of operationFiles.entries()) {
      const dataContractsImport = createDataContractsImport(
        operationFile.route,
        generatorOutput.configuration,
        modelNames,
      );
      const runtimeNames = createOperationRuntimeNames(dataContractsImport.names);
      let operationContent = String(await generatorOutput.renderTemplate(operationTemplate, {
        ...generatorOutput.configuration,
        route: operationFile.route,
        operationName: operationFile.operationName,
        runtimeNames,
      }));
      operationContent = operationContent
        .replace('__HTTP_CLIENT_IMPORTS__', createHttpClientImport(operationFile.route, runtimeNames))
        .replace('__DATA_CONTRACT_IMPORTS__', dataContractsImport.content);

      await writeFormattedFile(
        activeFormatter,
        writer,
        `operations/${operationFile.operationFileName}.ts`,
        operationContent,
      );

      const completed = index + 1;
      if (completed % 10 === 0 || completed === operationFiles.length) {
        tracker.update(completed, operationFiles.length);
      }
    }

    tracker.start('indexes');
    const operationExports = operationFiles.toSorted(compareOperationFiles).map(
      (operationFile) =>
        `export { ${operationFile.operationName} } from "./${operationFile.operationFileName}.js";`,
    );

    await writeFormattedFile(
      activeFormatter,
      writer,
      'operations/index.ts',
      operationExports.length ? operationExports.join('\n') : 'export {};',
    );

    await writeFormattedFile(
      activeFormatter,
      writer,
      'operations-tree.ts',
      createOperationTreeContent(generatorOutput.configuration, operationFiles),
    );

    await writeFormattedFile(
      activeFormatter,
      writer,
      'index.ts',
      [
        'export { createApiClient } from "./create-api-client.js";',
        'export type { ApiOperation, ApiTree, BoundApi } from "./create-api-client.js";',
        'export type * from "./data-contracts.js";',
        'export { ApiError, ContentType, HttpClient } from "./http-client.js";',
        'export type { ApiConfig, ApiRequestClient, CancelToken, ErrorInterceptor, FetchLike, FullRequestParams, HttpResponse, ParamsSerializer, QueryParamsType, RequestContext, RequestInterceptor, RequestParams, ResponseFormat, ResponseInterceptor, ResponseParser } from "./http-client.js";',
        'export { operationsTree } from "./operations-tree.js";',
        'export type { OperationsTree } from "./operations-tree.js";',
        'export * from "./operations/index.js";',
        'export * as operations from "./operations/index.js";',
      ].join('\n'),
    );

    return {
      outputPath: outputDir,
      fileCount: writer.fileCount,
      modelCount: generatorOutput.configuration.modelTypes.length,
      operationCount: operationFiles.length,
      ...tracker.finish(),
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Ошибка генерации: ${translateGenerationErrorMessage(message)}`);
  } finally {
    formatter?.shutdown();
  }
}
