import {
  generateApi as swaggerGenerateApi,
  type GenerateApiConfiguration,
  type GenerateApiOutput,
  type ModelType,
  type ParsedRoute,
} from 'swagger-typescript-api';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, rename, rm } from 'node:fs/promises';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { GeneratorConfig } from './config.js';
import { readTextFile, writeFileWithDirs } from './utils/file.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GENERATED_FILE_PREFIX = `/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */`;

type OperationFileInfo = {
  route: ParsedRoute;
  operationName: string;
  operationFileName: string;
};

type OperationTreeGroup = {
  moduleName: string;
  operations: OperationFileInfo[];
};

type PreparedSpecification = {
  spec: Record<string, unknown>;
  restoreTags: (configuration: GenerateApiConfiguration) => void;
};

const DEFAULT_BASE_URL_DECLARATION = "public baseUrl = '';";

const RESERVED_IDENTIFIERS = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
  'await',
  'arguments',
  'eval',
  'let',
  'static',
  'implements',
  'interface',
  'package',
  'private',
  'protected',
  'public',
]);

const PROTOTYPE_PROPERTY_NAMES = new Set(Object.getOwnPropertyNames(Object.prototype));
const HTTP_METHODS = new Set(['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']);

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function toWords(value: string): string[] {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}

function toCamelCase(value: string): string {
  const words = toWords(value);
  if (!words.length) {
    return '';
  }

  const [firstWord = '', ...restWords] = words;
  return [
    firstWord.toLowerCase(),
    ...restWords.map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()),
  ].join('');
}

function toKebabCase(value: string): string {
  return toWords(value).map((word) => word.toLowerCase()).join('-');
}

function createFallbackRouteName(route: ParsedRoute): string {
  return toCamelCase(`${route.raw.method} ${route.raw.route}`) || 'operation';
}

function createSafeIdentifier(value: string, fallback: string): string {
  const identifier = value.replace(/[^A-Za-z0-9_$]/g, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '');
  const safeIdentifier = identifier || fallback;

  if (RESERVED_IDENTIFIERS.has(safeIdentifier)) {
    const safeFallback = fallback.replace(/[^A-Za-z0-9_$]/g, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '');

    if (safeFallback && !RESERVED_IDENTIFIERS.has(safeFallback) && /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(safeFallback)) {
      return safeFallback;
    }

    return `${safeIdentifier}Operation`;
  }

  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(safeIdentifier)) {
    return safeIdentifier;
  }

  return `operation${safeIdentifier.charAt(0).toUpperCase()}${safeIdentifier.slice(1)}`;
}

function createUniqueName(baseName: string, usedNames: Set<string>): string {
  let name = baseName;
  let counter = 2;

  while (usedNames.has(name)) {
    name = `${baseName}${counter}`;
    counter += 1;
  }

  usedNames.add(name);
  return name;
}

function getAllRoutes(configuration: GenerateApiConfiguration): ParsedRoute[] {
  return [
    ...(configuration.routes.outOfModule || []),
    ...(configuration.routes.combined || []).flatMap(({ routes }) => routes || []),
  ];
}

function createOperationFiles(routes: ParsedRoute[]): OperationFileInfo[] {
  const usedOperationNames = new Set<string>();
  const usedFileNames = new Set<string>();

  return routes.map((route) => {
    const fallbackRouteName = createFallbackRouteName(route);
    const operationName = createUniqueName(
      createSafeIdentifier(route.routeName.usage || fallbackRouteName, fallbackRouteName),
      usedOperationNames,
    );
    const operationFileName = createUniqueName(
      toKebabCase(operationName) || toKebabCase(fallbackRouteName) || 'operation',
      usedFileNames,
    );

    return {
      route,
      operationName,
      operationFileName,
    };
  });
}

function createDataContractsImport(content: string, modelTypes: ModelType[]): string {
  const importedNames = modelTypes
    .map(({ name }) => name)
    .filter((name) => new RegExp(`(^|[^A-Za-z0-9_$])${escapeRegExp(name)}(?![A-Za-z0-9_$])`, 'm').test(content))
    .sort((a, b) => a.localeCompare(b));

  if (!importedNames.length) {
    return '';
  }

  return `import type { ${importedNames.join(', ')} } from "../data-contracts.js";`;
}

function createHttpClientImport(content: string): string {
  const imports = ['import type { ApiRequestClient, RequestParams } from "../http-client.js";'];

  if (content.includes('ContentType.')) {
    imports.unshift('import { ContentType } from "../http-client.js";');
  }

  return imports.join('\n');
}

function createObjectPropertyKey(name: string): string {
  return JSON.stringify(name);
}

function createOperationTreePropertyName(operationFile: OperationFileInfo): string {
  return operationFile.route.routeName.usage || operationFile.operationName;
}

function createOperationTreeContent(configuration: GenerateApiConfiguration, operationFiles: OperationFileInfo[]): string {
  const operationByRoute = new Map(operationFiles.map((operationFile) => [operationFile.route, operationFile]));
  const imports = operationFiles.map(
    (operationFile) =>
      `import { ${operationFile.operationName} } from "./operations/${operationFile.operationFileName}.js";`,
  );
  const outOfModuleOperations = (configuration.routes.outOfModule || [])
    .map((route) => operationByRoute.get(route))
    .filter((operationFile): operationFile is OperationFileInfo => Boolean(operationFile));
  const operationTreeGroups: OperationTreeGroup[] = (configuration.routes.combined || []).map(({ moduleName, routes }) => ({
    moduleName,
    operations: (routes || [])
      .map((route) => operationByRoute.get(route))
      .filter((operationFile): operationFile is OperationFileInfo => Boolean(operationFile)),
  }));
  const lines = [
    ...imports,
    '',
    'export const operationsTree = {',
  ];

  const rootPropertyNames = new Set<string>();

  for (const operationFile of outOfModuleOperations) {
    const propertyName = createUniqueName(createOperationTreePropertyName(operationFile), rootPropertyNames);
    lines.push(`  ${createObjectPropertyKey(propertyName)}: ${operationFile.operationName},`);
  }

  for (const { moduleName, operations } of operationTreeGroups) {
    const groupName = createUniqueName(moduleName, rootPropertyNames);
    lines.push(`  ${createObjectPropertyKey(groupName)}: {`);
    const groupPropertyNames = new Set<string>();

    for (const operationFile of operations) {
      const propertyName = createUniqueName(createOperationTreePropertyName(operationFile), groupPropertyNames);
      lines.push(`    ${createObjectPropertyKey(propertyName)}: ${operationFile.operationName},`);
    }

    lines.push('  },');
  }

  lines.push('} as const;', '', 'export type OperationsTree = typeof operationsTree;');

  return lines.join('\n');
}

async function renderTemplateFile(
  generatorOutput: GenerateApiOutput,
  templatePath: string,
  data: unknown,
): Promise<string> {
  const template = await readTextFile(templatePath);
  return String(await generatorOutput.renderTemplate(template, data as Record<string, unknown>));
}

function getEmbeddedClientSourcePath(templatesPath: string, fileName: string): string {
  const sourcePath = resolve(__dirname, 'client', fileName);
  return existsSync(sourcePath) ? sourcePath : resolve(templatesPath, fileName);
}

async function renderHttpClient(templatesPath: string, spec: Record<string, unknown>): Promise<string> {
  const source = await readTextFile(getEmbeddedClientSourcePath(templatesPath, 'http-client.ts'));
  const servers = Array.isArray(spec.servers) ? spec.servers : [];
  const firstServer = servers[0];
  const baseUrl = firstServer && typeof firstServer === 'object' && 'url' in firstServer
    ? (firstServer as { url?: unknown }).url
    : '';
  const replacement = `public baseUrl = ${JSON.stringify(typeof baseUrl === 'string' ? baseUrl : '')};`;

  if (
    !source.includes(DEFAULT_BASE_URL_DECLARATION) ||
    source.indexOf(DEFAULT_BASE_URL_DECLARATION) !== source.lastIndexOf(DEFAULT_BASE_URL_DECLARATION)
  ) {
    throw new Error('Не удалось подготовить HttpClient: ожидается одно стандартное объявление baseUrl.');
  }

  return source.replace(DEFAULT_BASE_URL_DECLARATION, replacement);
}

async function writeFormattedFile(
  generatorOutput: GenerateApiOutput,
  filePath: string,
  content: string,
): Promise<void> {
  const formattedContent = await generatorOutput.formatTSContent(`${GENERATED_FILE_PREFIX}\n\n${content}`);
  await writeFileWithDirs(filePath, formattedContent);
}

async function replaceGeneratedOutput(outputDir: string, stagingDir: string): Promise<void> {
  const outputParent = dirname(outputDir);
  const backupDir = join(outputParent, `.${basename(outputDir)}-backup-${process.pid}-${Date.now()}`);
  const hasExistingOutput = existsSync(outputDir);

  try {
    if (hasExistingOutput) {
      await rename(outputDir, backupDir);
    }

    await rename(stagingDir, outputDir);
    await rm(backupDir, { recursive: true, force: true });
  } catch (error) {
    if (hasExistingOutput && !existsSync(outputDir) && existsSync(backupDir)) {
      await rename(backupDir, outputDir);
    }

    throw error;
  }
}

function validateSpecification(spec: Record<string, unknown>): void {
  if (typeof spec.openapi !== 'string' && typeof spec.swagger !== 'string') {
    throw new Error('Не указана версия OpenAPI (`openapi`) или Swagger (`swagger`).');
  }

  if (!spec.info || typeof spec.info !== 'object' || Array.isArray(spec.info)) {
    throw new Error('OpenAPI спецификация должна содержать объект `info`.');
  }

  if (!spec.paths || typeof spec.paths !== 'object' || Array.isArray(spec.paths)) {
    throw new Error('OpenAPI спецификация должна содержать объект `paths`.');
  }
}

function prepareSpecification(spec: Record<string, unknown>): PreparedSpecification {
  const internalToOriginalTag = new Map<string, string>();
  const originalToInternalTag = new Map<string, string>();
  const paths = spec.paths as Record<string, unknown>;
  let tagIndex = 0;

  for (const pathItem of Object.values(paths)) {
    if (!pathItem || typeof pathItem !== 'object' || Array.isArray(pathItem)) {
      continue;
    }

    for (const [method, operation] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method.toLowerCase()) || !operation || typeof operation !== 'object' || Array.isArray(operation)) {
        continue;
      }

      const tags = (operation as { tags?: unknown }).tags;
      if (!Array.isArray(tags)) {
        continue;
      }

      (operation as { tags: unknown[] }).tags = tags.map((tag) => {
        if (typeof tag !== 'string' || !PROTOTYPE_PROPERTY_NAMES.has(tag)) {
          return tag;
        }

        const existingInternalTag = originalToInternalTag.get(tag);
        if (existingInternalTag) {
          return existingInternalTag;
        }

        const internalTag = `restApiCodegenTag${tagIndex++}`;
        originalToInternalTag.set(tag, internalTag);
        internalToOriginalTag.set(internalTag, tag);
        return internalTag;
      });
    }
  }

  return {
    spec,
    restoreTags: (configuration) => {
      for (const group of configuration.routes.combined || []) {
        const originalTag = internalToOriginalTag.get(group.moduleName);
        if (originalTag) {
          group.moduleName = originalTag;
        }

        for (const route of group.routes || []) {
          route.raw.tags = (route.raw.tags || []).map((tag) => internalToOriginalTag.get(tag) || tag);
        }
      }
    },
  };
}

async function loadSpecification(inputPath: string): Promise<Record<string, unknown>> {
  const isUrl = inputPath.startsWith('http://') || inputPath.startsWith('https://');
  let content: string;

  if (isUrl) {
    let response: Response;

    try {
      response = await fetch(inputPath);
    } catch (error) {
      const details = error instanceof Error ? translateGenerationErrorMessage(error.message) : String(error);
      throw new Error(
        `Не удалось подключиться к OpenAPI спецификации: ${inputPath}. ` +
          `Проверьте доступность URL и сетевое подключение. Детали: ${details}`,
      );
    }

    if (!response.ok) {
      throw new Error(
        `Не удалось загрузить OpenAPI спецификацию из ${inputPath}: ${response.status} ${response.statusText}`,
      );
    }

    content = await response.text();
  } else {
    content = await readTextFile(resolve(inputPath));
  }

  let specification: unknown;

  try {
    specification = JSON.parse(content) as unknown;
  } catch (error) {
    const details = error instanceof Error ? error.message : String(error);
    throw new Error(`Не удалось распарсить OpenAPI спецификацию как JSON. Детали: ${details}`);
  }

  if (!specification || typeof specification !== 'object' || Array.isArray(specification)) {
    throw new Error('OpenAPI спецификация должна быть JSON-объектом.');
  }

  const spec = specification as Record<string, unknown>;
  validateSpecification(spec);
  return spec;
}

function translateGenerationErrorMessage(message: string): string {
  return message
    .replace(
      'Unable to connect. Is the computer able to access the url?',
      'Не удалось подключиться к URL. Проверьте доступность OpenAPI спецификации и сетевое подключение.',
    )
    .replace('fetch failed', 'не удалось выполнить сетевой запрос')
    .replace('request timeout', 'истекло время ожидания запроса')
    .replace('socket hang up', 'соединение было разорвано')
    .replace('ECONNREFUSED', 'соединение отклонено')
    .replace('ENOTFOUND', 'хост не найден')
    .replace('ETIMEDOUT', 'истекло время ожидания соединения');
}

/**
 * Генерация API клиента из OpenAPI спецификации
 */
export async function generate(config: GeneratorConfig): Promise<void> {
  const templatesPath = resolve(__dirname, 'templates');

  if (!existsSync(templatesPath)) {
    throw new Error(
      `Директория шаблонов не найдена: ${templatesPath}. ` +
        'Проверьте, что пакет собран корректно (npm run build).',
    );
  }

  try {
    const outputDir = resolve(config.outputPath);
    const outputParent = dirname(outputDir);
    const spec = await loadSpecification(config.inputPath);
    const preparedSpecification = prepareSpecification(spec);
    const generatorOutput = await swaggerGenerateApi({
      spec: preparedSpecification.spec,
      httpClientType: 'fetch',
      modular: false,
      templates: templatesPath,
      generateClient: false,
      generateRouteTypes: false,
      generateUnionEnums: true,
      extractRequestParams: true,
      extractRequestBody: true,
      extractEnums: true,
      cleanOutput: false,
      unwrapResponseData: true,
      defaultResponseAsSuccess: true,
      enumNamesAsValues: false,
      moduleNameFirstTag: true,
      extraTemplates: [],
      addReadonly: false,
      sortTypes: false,
      sortRoutes: false,
      extractResponseError: false,
      fixInvalidEnumKeyPrefix: 'KEY',
      silent: true,
      defaultResponseType: 'void',
      typePrefix: '',
      typeSuffix: '',
      enumKeyPrefix: '',
      enumKeySuffix: '',
      extractingOptions: {
        requestBodySuffix: ['Payload', 'Body', 'Input'],
        requestParamsSuffix: ['Params'],
        responseBodySuffix: ['Data', 'Result', 'Output'],
        responseErrorSuffix: ['Error', 'Fail', 'Fails', 'ErrorData', 'HttpError', 'BadResponse'],
      },
      hooks: {
        onFormatRouteName: (_routeInfo: unknown, templateRouteName: string) => {
          const match = templateRouteName.match(/^(\w+)Controller(\w+)$/);
          const methodName = match?.[2];

          return methodName
            ? methodName.charAt(0).toLowerCase() + methodName.slice(1)
            : templateRouteName;
        },
      },
      output: false,
      fileName: 'index.ts',
    } as Parameters<typeof swaggerGenerateApi>[0]) as unknown as GenerateApiOutput;
    preparedSpecification.restoreTags(generatorOutput.configuration);

    await mkdir(outputParent, { recursive: true });
    const stagingDir = await mkdtemp(join(outputParent, `.${basename(outputDir)}-staging-`));

    try {
      await writeFormattedFile(
        generatorOutput,
        join(stagingDir, 'data-contracts.ts'),
        await renderTemplateFile(generatorOutput, join(templatesPath, 'data-contracts.ejs'), generatorOutput.configuration),
      );

      await writeFormattedFile(
        generatorOutput,
        join(stagingDir, 'http-client.ts'),
        await renderHttpClient(templatesPath, spec),
      );

      await writeFormattedFile(
        generatorOutput,
        join(stagingDir, 'create-api-client.ts'),
        await readTextFile(getEmbeddedClientSourcePath(templatesPath, 'create-api-client.ts')),
      );

      const operationTemplatePath = join(templatesPath, 'operation.ejs');
      const operationFiles = createOperationFiles(getAllRoutes(generatorOutput.configuration));
      const operationExports: string[] = [];

      for (const operationFile of operationFiles) {
        let operationContent = await renderTemplateFile(generatorOutput, operationTemplatePath, {
          ...generatorOutput.configuration,
          route: operationFile.route,
          operationName: operationFile.operationName,
        });
        operationContent = operationContent
          .replace('__HTTP_CLIENT_IMPORTS__', createHttpClientImport(operationContent))
          .replace('__DATA_CONTRACT_IMPORTS__', createDataContractsImport(operationContent, generatorOutput.configuration.modelTypes));

        await writeFormattedFile(
          generatorOutput,
          join(stagingDir, 'operations', `${operationFile.operationFileName}.ts`),
          operationContent,
        );

        operationExports.push(
          `export { ${operationFile.operationName} } from "./${operationFile.operationFileName}.js";`,
        );
      }

      await writeFormattedFile(
        generatorOutput,
        join(stagingDir, 'operations', 'index.ts'),
        operationExports.length ? operationExports.join('\n') : 'export {};',
      );

      await writeFormattedFile(
        generatorOutput,
        join(stagingDir, 'operations-tree.ts'),
        createOperationTreeContent(generatorOutput.configuration, operationFiles),
      );

      await writeFormattedFile(
        generatorOutput,
        join(stagingDir, 'index.ts'),
        [
          'export { createApiClient } from "./create-api-client.js";',
          'export type { ApiOperation, ApiTree, BoundApi } from "./create-api-client.js";',
          'export { ApiError, ContentType, HttpClient } from "./http-client.js";',
          'export type { ApiConfig, ApiRequestClient, CancelToken, ErrorInterceptor, FetchLike, FullRequestParams, HttpResponse, ParamsSerializer, QueryParamsType, RequestContext, RequestInterceptor, RequestParams, ResponseFormat, ResponseInterceptor, ResponseParser } from "./http-client.js";',
          'export type * from "./data-contracts.js";',
          'export { operationsTree } from "./operations-tree.js";',
          'export type { OperationsTree } from "./operations-tree.js";',
          'export * as operations from "./operations/index.js";',
          'export * from "./operations/index.js";',
        ].join('\n'),
      );

      await replaceGeneratedOutput(outputDir, stagingDir);
    } catch (error) {
      await rm(stagingDir, { recursive: true, force: true });
      throw error;
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Ошибка генерации: ${translateGenerationErrorMessage(message)}`);
  }
}
